INSERT INTO course VALUES(DEFAULT , "English",100,50);
INSERT INTO course VALUES(DEFAULT , "Mathematics 1",100,50);
INSERT INTO course VALUES(DEFAULT , "Mathematics 2",100,50);
INSERT INTO course VALUES(DEFAULT , "Arabic",100,50);
INSERT INTO course VALUES(DEFAULT , "Software Engineering 1",100,50);
INSERT INTO course VALUES(DEFAULT , "Software Engineering 2",100,50);
INSERT INTO course VALUES(DEFAULT , "Database",100,50);
INSERT INTO course VALUES(DEFAULT , "Datastructure",100,50);
INSERT INTO course VALUES(DEFAULT , "Logic",100,50);
INSERT INTO course VALUES(DEFAULT , "Computer Organization 1",100,50);
INSERT INTO course VALUES(DEFAULT , "System Analysis",100,50);
INSERT INTO course VALUES(DEFAULT , "Assembly",100,50);
INSERT INTO course VALUES(DEFAULT , "Operating Systems",100,50);
INSERT INTO course VALUES(DEFAULT , "Networks 1",100,50);
INSERT INTO course VALUES(DEFAULT , "Networks 2",100,50);
INSERT INTO course VALUES(DEFAULT , "Operation Research",100,50);