################################################
#
# FILE DESCRIPTION:
# Select couser name, number of question, max number of options
#
# CREATION DATE / BY:
# 15 Mars 2006 BY Abbas Adel
#
# LAST MODIFY / BY:
# 6 May 2006 BY Abbas Adel, Tanahy
#
# MODIFICATIONS:
# 1- Added TID to Question which references Teacher(TID);
# 2- Added `Date` to Teach
# 3- Added Exam and TakeExam tables 
# 4- CID to EID in Result
# 5- Added login Timestamp to teacher to save last login date
# 6- Added login Timestamp to student to save last login date
# 7- Added Message table to handle messages in the system
# 8- Added 'SubmitExam' table to handle group exams
#
#################################################
 
DROP DATABASE IF EXISTS mufic;
CREATE DATABASE mufic;
USE mufic;




DROP TABLE IF EXISTS Course;
CREATE TABLE Course 
(
	CID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CName varchar(50) NOT NULL,
	Max INTEGER(3) NOT NULL,
	Min INTEGER(3) NOT NULL,
	PRIMARY KEY(CID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS Teacher;
CREATE TABLE Teacher
(
	TID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	TName varchar(50) not null,
	Password varchar(20) not null,
	Degree ENUM('Demonstrator','Lecturer','Assistant Lecturer','Proffessor') NOT NULL DEFAULT 'Lecturer',
        Birth DATE DEFAULT '0000-00-00',
        Address VARCHAR(45),
        Tell VARCHAR(10),
        Email varchar(20),
        `Date` date,
        login TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(TID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS Student;
CREATE TABLE Student
(
	SID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	SName varchar(50) NOT NULL,
	Password varchar(20) NOT NULL,
	Email varchar(45),
  Birth DATE DEFAULT '0000-00-00',
  Tell VARCHAR(10) NOT NULL,
  Address VARCHAR(80) NOT NULL,
  `Date` date,
  login TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(SID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS Message;
CREATE TABLE Message
(   
    MID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    UID INTEGER(10) UNSIGNED NOT NULL,
    `type` ENUM('exam','result','group'),
    Message varchar(255) NOT NULL,
    mdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID INTEGER(10) NOT NULL,
    `User` ENUM('student','teacher') NOT NULL,
    PRIMARY KEY(MID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS `Group`;
CREATE TABLE `Group`
(
	GID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	TID INTEGER(10) UNSIGNED NOT NULL,
	GName VARCHAR(25),
        `gdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (GID, TID),
	FOREIGN KEY (TID) REFERENCES Teacher(TID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS `Assign`;
CREATE TABLE `Assign`
(
	GID INTEGER(10) UNSIGNED NOT NULL,
	SID INTEGER(10) UNSIGNED NOT NULL,
	`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY (GID, SID), 
	FOREIGN KEY (SID) REFERENCES Student(SID),
	FOREIGN KEY (GID) REFERENCES `Group`(GID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS Teach;
CREATE TABLE Teach
(
	CID INTEGER(10) UNSIGNED not null,
	TID INTEGER(10) UNSIGNED not null,
        `Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (CID,TID),
	FOREIGN KEY (TID) REFERENCES Teacher(TID),
	FOREIGN KEY (CID) REFERENCES Course(CID) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS Question;
CREATE TABLE Question
(
	QID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CID INTEGER(10) UNSIGNED NOT NULL,
	OID INTEGER(10) UNSIGNED NOT NULL,
	TID INTEGER(10) UNSIGNED NOT NULL,
	Question varchar(100) NOT NULL,
	`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(QID),
	FOREIGN KEY (CID) REFERENCES Course(CID),
	FOREIGN KEY (TID) REFERENCES Teacher(TID)
	#FOREIGN KEY (OID) REFERENCES `Option`(OID)
	
)ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS `Option`;
CREATE TABLE `Option`
(
	OID INTEGER(10) UNSIGNED NOT NULL,
	QID INTEGER(10) UNSIGNED NOT NULL,	
	OName varchar(100) NOT NULL,	
	
	PRIMARY KEY(OID, QID),
	FOREIGN KEY(QID) REFERENCES Question(QID)

)ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS `Exam`;
CREATE TABLE `Exam`
(
	EID INTEGER(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CID INTEGER(10) UNSIGNED NOT NULL,	
        TID INTEGER(10) UNSIGNED NOT NULL,
	EName varchar(100) NOT NULL,	
	EDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        StartDate Date,
        EndDate Date,
	PRIMARY KEY(EID),
	FOREIGN KEY(CID) REFERENCES course(CID),
	FOREIGN KEY(TID) REFERENCES teacher(TID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS `TakeExam`;
CREATE TABLE `TakeExam`
(
        EID INTEGER(10) UNSIGNED NOT NULL,
	QID INTEGER(10) UNSIGNED NOT NULL,	
        PRIMARY KEY(EID ,QID),
        FOREIGN KEY(EID) REFERENCES exam(EID),
	FOREIGN KEY(QID) REFERENCES question(QID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `SubmitExam`;
CREATE TABLE `SubmitExam`
(
        EID INTEGER(10) UNSIGNED NOT NULL,
	GID INTEGER(10) UNSIGNED NOT NULL,
	StartDate Date,
        EndDate Date,
        Period  INTEGER(4),
        PRIMARY KEY(EID ,GID),
        FOREIGN KEY(EID) REFERENCES exam(EID),
	FOREIGN KEY(GID) REFERENCES `Group`(GID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;




DROP TABLE IF EXISTS `Result`;
CREATE TABLE `Result`
(
	SID INTEGER(10) UNSIGNED not null,
	EID INTEGER(10) UNSIGNED not null,
	Grade ENUM('A+','A','A-','B+','B','B-','C+','C','C-','F') NOT NULL,
	Mark 	INTEGER(3) UNSIGNED not null,
	`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (SID, EID),
	FOREIGN KEY (SID) REFERENCES Student(SID),
	FOREIGN KEY (EID) REFERENCES Exam(EID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

